config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  resources :products, except: [:index]
    resources :mid_category, only: :new
    resources :small_category, only: :new


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      "users/sessions"
  }
  devise_scope :user do
    get '/users', to: redirect("/users/sign_up")
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]do
    member do   
      get 'logout'
    end
  end  

  
 


  post '/products/:id/purchase',to: 'products#purchase'
  get 'products/new/mid_category', to: 'products#mid_category'
  get 'products/new/small_category', to: 'products#small_category'
 

  resources :products do
    member do
      post 'purchase'
      get 'buy'
      get 'purchased'
    end  
    get 'products/new/mid_category', to: 'products#mid_category'
    get 'products/new/small_category', to: 'products#small_category'
  end  
  
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :email, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday,  presence: true    
  has_one :address
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
 
  has_many :cards
  has_many :products
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from StandardError, with: :render_500

  def render_404(exception = nil)
    if exception
      logger.info "Rendering 404 with exception: #{exception.message}"
    end
    render template: "errors/error_404", status: 404, layout: 'application'
  end

  def render_500(exception = nil)
    if exception
      logger.info "Rendering 500 with exception: #{exception.message}"
    end
    render template: "errors/error_500", status: 500, layout: 'application'
  end

  def show; raise env["action_dispatch.exception"]; 
  end
  before_action :authenticate_user!
  def new_address
    @address = Address.new
  end  

  def new
    @user = User.new
  end

  
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    if @user.save
      session["devise.regist_data"]["user"].clear
      sign_in(:user, @user)
    else 
      render :new 
    end  
    
  end




  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
   
  def address_params
    params.require(:address).permit(:postal_code, :prefecture, :city, :block_number, :apartment_name)
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:logout]
  def show
  end


  def logout
  end
 
  private

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(
      :nickname,
      :introduction,
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage_side.html.haml
.side-content
  %nav.mypage-nav
    %ul.mypage-nav-list 
      %li 
        =link_to user_path(current_user.id), class: "mypage-nav-list-item" do
          マイページ
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          お知らせ
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          やることリスト
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          いいね！一覧
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          出品する
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          出品した商品 - 出品中
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          出品した商品 - 取引中
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          出品した商品 - 売却済み
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          購入した商品 - 取引中
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          購入した商品 - 過去の取引
          %i.fas.fa-angle-right              
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          ニュース一覧
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          評価一覧
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          ガイド
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-item" do
          お問い合わせ
          %i.fas.fa-angle-right

    %h3.mypage-nav-head-setting 設定
    %ul.mypage-nav-list-setting 
      %li
        =link_to "#", class: "mypage-nav-list-setting-item" do
          プロフィール
          %i.fas.fa-angle-right    
      %li
        =link_to "#", class: "mypage-nav-list-setting-item" do
          発送元・お届け先住所変更
          %i.fas.fa-angle-right  
      %li
        =link_to new_card_path, class: "mypage-nav-list-setting-item" do

          支払い方法
          %i.fas.fa-angle-right 
      %li
        =link_to "#", class: "mypage-nav-list-setting-item" do
          メール/パスワード
          %i.fas.fa-angle-right 
      %li
        =link_to "#", class: "mypage-nav-list-setting-item" do
          本人情報
          %i.fas.fa-angle-right
      %li
        =link_to "#", class: "mypage-nav-list-setting-item" do
          電話番号の確認
          %i.fas.fa-angle-right
      %li
        =link_to  logout_user_path, class: "mypage-nav-list-setting-item" do
          ログアウト
          %i.fas.fa-angle-right

app/views/users/card.html.haml
= render "users/mypage_side"
.mypage  
  %main.mypage-contents.clearfix
    .main-content
      .payment
        .payment-content
          .payment-content__title
            %h1.payment-header 支払い方法
          .payment-content__main
            .payment-content__creditcards
              %h2.payment-title クレジットカード一覧
            

app/views/users/logout.html.haml
=render "users/mypage_side"
.mypage
  %main.mypage-contents.clearfix
    .main-content
      .logout
        .logout-content
          =link_to destroy_user_session_path, method: :delete, class:"btn-default btn-red" do
            ログアウト

app/views/users/show.html.haml
= render "users/mypage_side"
.mypage  
  %main.mypage-contents.clearfix
    .main-content
      %section.user
        .user-link
          %figure
            .user-link__iconn
              = image_tag("material/icon/member_photo_noimage_thumb.png", class:"user-link__icon")
          %h2.user-link__name
            = @user.nickname
          .user-link__number
            評価  ５  出品数  ８
      %section.notification-todo
        %ul.tabs
          %li.select
            お知らせ
          %li
            やることリスト
        .tab-content-notification-todo
          %ul.notification-item-list
            %li.notification-item-link
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text 明日、8%還元クーポンの有効期限が切れます！タップして詳細を確認しましょう。
                %time
                  %i.icon-time
                  %span 1 時間前
              %i.icon-arrow-right
            %li.notification-item-link            
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text 事務局から個別メッセージ「《3日間限定！ポイント倍増》招待コード「あけおめ」を入力してメルペイ登録すると合計P2,000もらえる」
                %time
                  %i.icon-time
                  %span 1 時間前
              %i.icon-arrow-right
            %li.notification-item-link
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text 事務局から個別メッセージ「【対象者限定】セブン-イレブン初発送200円分ポイントプレゼント」
                %time
                  %i.icon-time
                  %span 1 日前
              %i.icon-arrow-right
            %li.notification-item-link
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text 《最大10万円相当》売れたら売上金が2倍のチャンス！本日スタート！
                %time
                  %i.icon-time
                  %span 1 日前
              %i.icon-arrow-right
            %li.notification-item-link
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text 3日後、8%還元クーポンの有効期限が切れます！タップして詳細を確認しましょう。
                %time
                  %i.icon-time
                  %span 2 日前
              %i.icon-arrow-right
            %li.mypage-go-list
              =link_to "#", class: "go" do
                一覧を見る
          %ul.notification-item-list.hide
            %li.notification-item-link
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text メールアドレスを確認してください。
                %time
                  %i.icon-time
                  %span 1 時間前
              %i.icon-arrow-right
            %li.notification-item-link            
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text メールアドレスを確認してください。
                %time
                  %i.icon-time
                  %span 1 時間前
              %i.icon-arrow-right
            %li.notification-item-link
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text 事務局から個別メッセージ「【対象者限定】セブン-イレブン初発送200円分ポイントプレゼント」
                %time
                  %i.icon-time
                  %span 1 日前
              %i.icon-arrow-right
            %li.notification-item-link
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text 《最大10万円相当》売れたら売上金が2倍のチャンス！本日スタート！
                %time
                  %i.icon-time
                  %span 1 日前
              %i.icon-arrow-right
            %li.notification-item-link
              .notification-item-link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .notification-item-link__body
                .notification-item-link__body--text 3日後、8%還元クーポンの有効期限が切れます！タップして詳細を確認しましょう。
                %time
                  %i.icon-time
                  %span 2 日前
              %i.icon-arrow-right
            %li.mypage-go-list
              =link_to "#", class: "go" do
                一覧を見る

      %section.transaction-hisory
        %h2.header 購入した商品
        %ul.transaction-tabs
          %li.select
            取引中
          %li
            過去の取引
        .tab-content-transaction
          %ul.tab-content-transaction__now
            %li.tab-content-transaction__notfound 取引中の商品がありません
          %ul.tab-content-transaction__old.hide
            %li.transaction-item__link
              .transaction-item__link__logo
                = image_tag("material/icon/icon_category.png", width:"48",height:"48")
              .transaction-item__link__body
                .transaction-item-link__body__text レース スカート  新品  RETRO GIRL M」 を購入しました。
                %i.icon-arrow-right
            %li.mypage-go-list
              =link_to "#", class: "go" do
                一覧を見る