config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  resources :products, except: [:index]
    resources :mid_category, only: :new
    resources :small_category, only: :new


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      "users/sessions"
  }
  devise_scope :user do
    get '/users', to: redirect("/users/sign_up")
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]do
    member do   
      get 'logout'
    end
  end  

  
 


  post '/products/:id/purchase',to: 'products#purchase'
  get 'products/new/mid_category', to: 'products#mid_category'
  get 'products/new/small_category', to: 'products#small_category'
 

  resources :products do
    member do
      post 'purchase'
      get 'buy'
      get 'purchased'
    end  
    get 'products/new/mid_category', to: 'products#mid_category'
    get 'products/new/small_category', to: 'products#small_category'
  end  
  
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  enum condition:   { brand_new: 0, near_to_unused: 1, no_scrach: 2, slight_scrach: 3, has_scrach: 4, bad_state: 5 }
  enum status:      { display: 0, sold: 1 }
  enum send_price:  { listing_person: 0, buyer_burden: 1 }
  enum shipping_date:    { early_ship: 0, mid_ship: 1, late_ship: 2 }
  enum size:         { small: 0, middle: 1, large: 2 }

  with_options presence: true do
    validates :name
    validates :description
    validates :price
    validates :condition
    validates :status
    validates :send_price
    validates :shipping_date
    validates :prefecture_id
    validates :category_id
    validates :size
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'payjp'
  before_action :set_product, except: [:index, :new, :create, :mid_category, :small_category, :buy, :purchase]
  before_action :set_product_purchase, only: [:buy, :purchase]
  before_action :set_categories, only: [:edit, :update]
  def index
    @product = Product.new
    @product.images.new
    @newProducts = Product.includes(:images).where(status: 0).order("RAND()").limit(4)
    @brandProducts = Product.includes(:images).where(status: 0).order("id DESC").limit(4)
    @soldProducts = Product.includes(:images).where(status: 1).order("id DESC").limit(4)
  end
  
  def new
    @parent = Category.where(ancestry: nil)
    if user_signed_in?
      @product = Product.new
      @product.images.new
      @parent = Category.where(ancestry: nil)
    else
      redirect_to root_path
    end
  end

  def create
    @product = Product.new(product_params)
    if params[:product][:images_attributes] && @product.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def show
  end

  def buy
    @address = Address.find_by(user_id: current_user.id)
  end


  def update
    if @product.update(product_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def mid_category
    @mid_categories = Category.where(ancestry: params[:big_category_id])
    render json: @mid_categories
  end

  def small_category
    @small_categories = Category.where(ancestry: "#{params[:big_category_id]}/#{params[:mid_category_id]}")
    render json: @small_categories
  end


  def purchase
    Payjp.api_key = "秘密鍵"
    Payjp::Charge.create(
      amount: 809, # 決済する値段
      card: params['payjp-token'], # フォームを送信すると作成・送信されてくるトークン
      currency: 'jpy'
    )
    @product.update(status: 1)
    redirect_to  buy_product_path
  else 
    flash[:notice] = "payjp以外が原因でクレジットカードでの支払いに失敗しました。"
    render :show
    end

  end
  private
  def product_params
    params.require(:product).permit(:name, :price, :description, :size, :brand, :status, :condition, :send_price, 
                                    :shipping_date, images_attributes: [:image])
                            .merge(user_id: current_user.id, category_id: params[:product][:category_id],
                              prefecture_id: params[:product][:prefecture], status: 0)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_product_purchase
    @product = Product.find(params[:id])
  end

  def set_categories
    @categories = Category.where(ancestry: nil)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_number1.html.haml
%section.mainVisual
  .content
    %h2.content__subtitle
      人生を変えるフリマアプリ
    .content__text
      %p
        FURIMAはだれでもかんたんに出品・購入できる
        %br
          フリマアプリです
    .content__btn
      = link_to "#" ,class: "content__btn" do
        = image_tag "app-store.svg"
      = link_to (image_tag "gougleplay.svg"),"#",class: "content__btn"
  .picture

%section.topIntroduction
  %h2.subtitle
    FURIMAが選ばれる3つの理由
    .subtitle__underLine
  .lists
    %li.lists__list
      .lists__list__pict
        %span.lists__list__pict__number1
          1
        .lists__list__pict__image
          .list__pict
            = image_tag "material/pict/pict-reason-01.jpg",class: "list__pict"
      %h3.lists__list__text
        %span 
          3分
        ですぐに出品
      %p.list__description
        スマホで入力するだけで簡単に出品できる!
    %li.lists__list
      .lists__list__pict
        %span.lists__list__pict__number2
          2
        .lists__list__pict__image
          .list__pict
            = image_tag "material/pict/pict-reason-02.jpg",class: "list__pict"
      %h3.lists__list__text
        %span
          シンプル
         で使いやすい
      %p.list__description
        めんどくさい入力は必要なく,検索も購入もスムーズ!
    %li.lists__list
      .lists__list__pict
        %span.lists__list__pict__number3
          3
        .lists__list__pict__image
          .list__pict
            = image_tag "material/pict/pict-reason-03.jpg",class: "list__pict"
      %h3.lists__list__text
        手数料
        %span 
          業界最安
      .list__description
        最大3%お得に出品&購入!

app/views/products/_number2.html.haml
%section.topMiddleDl
  .topMiddleDl__inner
    %h2.topMiddleDl__inner--subtitle 会員数日本一位
    %p.topMiddleDl__inner--text
      FURIMAは、フリマアプリで最も人気。
      %br/
      出品・購入回数も業界最多です！
      %br/
      ほしかったあの商品に出会えるかもしれません。
    .topMiddleDl__inner__btn
      = link_to "#",class: "topMiddleDl__inner__btn__link" do
        = image_tag "app-store.svg",class: "topMiddleDl__inner__btn--link--img"
      = link_to "#",class: "topMiddleDl__inner__btn__link" do
        = image_tag "gougleplay.svg",class: "topMiddleDl__inner__btn--link--img"

  -# ここから2ブロック目
%section.topKeyFeatures
  %h2.head
    FURIMAの特徴
    .head__line
  .items
    %section.items__item
      %figure.items__item__img
        = image_tag "material/icon/icon-01.png",class: "tag"
      %h3.items__item__subtitle 簡単に売り買いできる
      %p.items__item__detail
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    %section.items__item
      %figure.items__item__img
        = image_tag "material/icon/icon-03.png",class: "tag"
      %h3.items__item__subtitle 売上金は即日振込みに対応
      %p.items__item__detail
        午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
    %section.items__item
      %figure.items__item__img
        = image_tag "material/icon/icon-04.png",class: "tag"
      %h3.items__item__subtitle 様々な支払いに対応
      %p.items__item__detail
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/products/_number3.html.haml
%section.pickupContainer
  %h2.pickupContainer__head
    ピックアップカテゴリー
  .pickupContainer__productBox
    .pickupContainer__productBox__head
      =link_to "#" do
        %h3.title
          新規投稿商品
    .pickupContainer__productBox__lists
      .pickupContainer__productBox__lists__list
        - @brandProducts.each do |product|
          = link_to product_path(product), class: "listBtn" do
            %figure.pickupContainer__productBox__lists__list__a--img
              = image_tag product.images[0].image.url,class: "pickupContainer__productBox__lists__list__a--img__pice"
            .pickupContainer__productBox__lists__list__a__body
              %h3.pickupContainer__productBox__lists__list__a__body__name
                = product.name
              .pickupContainer__productBox__lists__list__a__body__details
                %ul
                  %li
                    = product.price
                    円
                  %li
                  %i.like
                %p
                  （税込）


-# ピックアップブランド
%section.pickupContainer
  %h2.pickupContainer__head
    ランダムピックアップ
  .pickupContainer__productBox
    .pickupContainer__productBox__head
      =link_to "#" do
        %h3.title
          アーカイバ
    .pickupContainer__productBox__lists
      .pickupContainer__productBox__lists__list
        - @newProducts.each do |product|
          = link_to product_path(product), class: "listBtn" do
            %figure.pickupContainer__productBox__lists__list__a--img
              = image_tag product.images[0].image.url, alt: "image_url",class: "pickupContainer__productBox__lists__list__a--img__pice"
            .pickupContainer__productBox__lists__list__a__body
              %h3.pickupContainer__productBox__lists__list__a__body__name
                = product.name
              .pickupContainer__productBox__lists__list__a__body__details
                %ul
                  %li
                    = product.price
                    円
                  %li
                    %i.like
                %p
                  （税込）

-# 売り切れ
%section.pickupContainer
  %h2.pickupContainer__head
    SOLD OUT
  .pickupContainer__productBox
    .pickupContainer__productBox__head
      =link_to "#" do
        %h3.title
          売却済み
    .pickupContainer__productBox__lists
      .pickupContainer__productBox__lists__list
        - @soldProducts.each do |product|
          = link_to product_path(product), class: "listBtn" do
            %figure.pickupContainer__productBox__lists__list__a--img
              = image_tag product.images[0].image.url, alt: "image_url",class: "pickupContainer__productBox__lists__list__a--img__pice"
            .pickupContainer__productBox__lists__list__a__body
              %h3.pickupContainer__productBox__lists__list__a__body__name
                = product.name
              .pickupContainer__productBox__lists__list__a__body__details
                %ul
                  %li
                    = product.price
                    円
                  %li
                    %i.like
                %p
                  （税込）
            .sold
              .sold__inner
                SOLD

app/views/products/_show-sign_in.html.haml
.brand-box
  %ul.brand-box__lists
    %li.brand-box__lists__list1
      = link_to root_path, class: "brand-box__lists__list1__link1" do
        FURIMA
      >
    %li.brand-box__lists__list2
      = @product.category.parent.parent.name

      >
    %li.brand-box__lists__list3
      = @product.category.parent.name

      >
    %li.brand-box__lists__list4
      = @product.category.name

      >
    %li.brand-box__lists__list5
      .brand-box__lists__list5--individual-product
        = @product.name

.details__content
  .details__content-box
    .detail
      .detail__name
        = @product.name
      %ul.detail__main__img
        %li
          = image_tag @product.images[0].image.url, class: "detail__main__img__image"
          %ul
            - @product.images.each do |image|
              %li
                = image_tag image.image.url, size: "70x70" , class: "show-img"
      .detail__price
        = @product.price
        円
        = form_with url: "/products/#{@product.id}/purchase", method: "post" do
          :plain
            <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="pk_test_6be7aa4a70675cef52cc1233"></script>
        %p (税込) 送料込み

      .detail__product__name
        = @product.name

      .detail__product__description
        = @product.description
      .detail__table
      
        %table
          %tbody
            %tr
              %th
                出品者
              %td
                = @product.user.nickname
            %tr
              %th
                カテゴリー
              %td
                = @product.category.parent.parent.name
                %br
                = @product.category.parent.name
                %br
                = @product.category.name
                  
            %tr
              %th
                ブランド
              %td
                = @product.brand
            %tr
              %th
                商品のサイズ
              %td
                = @product.size_i18n
            %tr
              %th
                商品の状態
              %td
                = @product.condition_i18n
            %tr
              %th
                配送料の負担
              %td
                = @product.send_price_i18n
            %tr
              %th
                発送元の地域
              %td
                = @product.prefecture.name
            %tr
              %th
                発送日の目安
              %td
                = @product.shipping_date_i18n
  .links
    .links__around
      = link_to "#", class: "links__around__ahead" do
        < 前の商品
      = link_to "#", class: "links__around__behind" do
        後ろの商品 >
    .links__category
      = link_to "#", class: "links__category__related" do
        = "#{@product.category.parent.parent.name} をもっと見る"
    - if current_user.id == @product.user_id
      = link_to "商品を編集する", edit_product_path(@product), class: "edit-btn"
      = link_to "商品を削除する", product_path(params[:id]), method: :delete, class: "delete-btn"
    - else
      = link_to buy_product_path(@product.id), class: "buy-btn" do
        購入画面へ

app/views/products/_show-sign_out.html.haml
.brand-box
  %ul.brand-box__lists
    %li.brand-box__lists__list1
      = link_to root_path, class: "brand-box__lists__list1__link1" do
        FURIMA
      >
    %li.brand-box__lists__list2
      = @product.category.parent.parent.name

      >
    %li.brand-box__lists__list3
      = @product.category.parent.name

      >
    %li.brand-box__lists__list4
      = @product.category.name

      >
    %li.brand-box__lists__list5
      .brand-box__lists__list5--individual-product
        = @product.name

.details__content
  .details__content-box
    .detail
      .detail__name
        = @product.name
      %ul.detail__main__img
        %li
          = image_tag @product.images[0].image.url, class: "detail__main__img__image"
          %ul
            - @product.images.each do |image|
              %li
                = image_tag image.image.url, size: "70x70" , class: "show-img"
      .detail__price
        = @product.price
        円
      
        %p (税込) 送料込み

      .detail__product__name
        = @product.name

      .detail__product__description
        = @product.description
      .detail__table
      
        %table
          %tbody
            %tr
              %th
                出品者
              %td
                = @product.user.nickname
            %tr
              %th
                カテゴリー
              %td
                = @product.category.parent.parent.name
                %br
                = @product.category.parent.name
                %br
                = @product.category.name
                  
            %tr
              %th
                ブランド
              %td
                = @product.brand
            %tr
              %th
                商品のサイズ
              %td
                = @product.size_i18n
            %tr
              %th
                商品の状態
              %td
                = @product.condition_i18n
            %tr
              %th
                配送料の負担
              %td
                = @product.send_price_i18n
            %tr
              %th
                発送元の地域
              %td
                = @product.prefecture.name
            %tr
              %th
                発送日の目安
              %td
                = @product.shipping_date_i18n
  .links
    .links__around
      = link_to "#", class: "links__around__ahead" do
        < 前の商品
      = link_to "#", class: "links__around__behind" do
        後ろの商品 >
    .links__category
      = link_to "#", class: "links__category--related" do
        = "#{@product.category.parent.parent.name} をもっと見る"

app/views/products/_show-sign_out_sold_out.html.haml
.brand-box
  %ul.brand-box__lists
    %li.brand-box__lists__list1
      = link_to root_path, class: "brand-box__lists__list1__link1" do
        FURIMA
      >
    %li.brand-box__lists__list2
      = @product.category.parent.parent.name

      >
    %li.brand-box__lists__list3
      = @product.category.parent.name

      >
    %li.brand-box__lists__list4
      = @product.category.name

      >
    %li.brand-box__lists__list5
      .brand-box__lists__list5--individual-product
        = @product.name

.details__content
  .details__content-box
    .detail
      .detail__name
        = @product.name
      %ul.detail__main__img
        %li
          = image_tag @product.images[0].image.url, class: "detail__main__img__image"
          .sold__out
            .sold__out__show 
              SOLD
          %ul
            - @product.images.each do |image|
              %li
                = image_tag image.image.url, size: "70x70" , class: "show-img"
      .detail__price
        = @product.price
        円
      
        %p (税込) 送料込み

      .detail__product__name
        = @product.name

      .detail__product__description
        = @product.description
      .detail__table
      
        %table
          %tbody
            %tr
              %th
                出品者
              %td
                = @product.user.nickname
            %tr
              %th
                カテゴリー
              %td
                = @product.category.parent.parent.name
                %br
                = @product.category.parent.name
                %br
                = @product.category.name
                  
            %tr
              %th
                ブランド
              %td
                = @product.brand
            %tr
              %th
                商品のサイズ
              %td
                = @product.size_i18n
            %tr
              %th
                商品の状態
              %td
                = @product.condition_i18n
            %tr
              %th
                配送料の負担
              %td
                = @product.send_price_i18n
            %tr
              %th
                発送元の地域
              %td
                = @product.prefecture.name
            %tr
              %th
                発送日の目安
              %td
                = @product.shipping_date_i18n
  .links
    .links__around
      = link_to "#", class: "links__around__ahead" do
        < 前の商品
      = link_to "#", class: "links__around__behind" do
        後ろの商品 >
    .links__category
      = link_to "#", class: "links__category--related" do
        = "#{@product.category.parent.parent.name} をもっと見る"

app/views/products/_show-sold_out.html.haml
.brand-box
  %ul.brand-box__lists
    %li.brand-box__lists__list1
      = link_to root_path, class: "brand-box__lists__list1__link1" do
        FURIMA
      >
    %li.brand-box__lists__list2
      = @product.category.parent.parent.name

      >
    %li.brand-box__lists__list3
      = @product.category.parent.name

      >
    %li.brand-box__lists__list4
      = @product.category.name

      >
    %li.brand-box__lists__list5
      .brand-box__lists__list5--individual-product
        = @product.name

.details__content
  .details__content-box
    .detail
      .detail__name
        = @product.name
      %ul.detail__main__img
        %li
          = image_tag @product.images[0].image.url, class: "detail__main__img__image"
          .sold__out
            .sold__out__show 
              SOLD
          %ul
            - @product.images.each do |image|
              %li
                = image_tag image.image.url, size: "70x70" , class: "show-img"
      .detail__price
        = @product.price
        円
      
        %p (税込) 送料込み

      .detail__product__name
        = @product.name

      .detail__product__description
        = @product.description
      .detail__table
      
        %table
          %tbody
            %tr
              %th
                出品者
              %td
                = @product.user.nickname
            %tr
              %th
                カテゴリー
              %td
                = @product.category.parent.parent.name
                %br
                = @product.category.parent.name
                %br
                = @product.category.name
                  
            %tr
              %th
                ブランド
              %td
                = @product.brand
            %tr
              %th
                商品のサイズ
              %td
                = @product.size_i18n
            %tr
              %th
                商品の状態
              %td
                = @product.condition_i18n
            %tr
              %th
                配送料の負担
              %td
                = @product.send_price_i18n
            %tr
              %th
                発送元の地域
              %td
                = @product.prefecture.name
            %tr
              %th
                発送日の目安
              %td
                = @product.shipping_date_i18n
  .links
    .links__around
      = link_to "#", class: "links__around__ahead" do
        < 前の商品
      = link_to "#", class: "links__around__behind" do
        後ろの商品 >
    .links__category
      = link_to "#", class: "links__category--related" do
        = "#{@product.category.parent.parent.name} をもっと見る"
    - if current_user.id == @product.user_id
      = link_to "商品を編集する", edit_product_path(@product), class: "edit-btn"
      = link_to "商品を削除する", product_path(params[:id]), method: :delete, class: "delete-btn"
    - else
      = link_to "#", class: "sold-btn" do
        売却済み

app/views/products/buy.html.haml
%main.buy-main 
  = form_tag(action: :purchase, method: :post) do
    .buy-item-container
      %h2.buy-item-head 購入内容の確認
      %section.buy-content.buy-item
        .buy-content-inner
          .buy-item-box
            .buy-item-image
              = image_tag @product.images[0].image.url, class: "detail__main__img__image"
            .buy-item-detail
              %p.buy-item-name
                =@product.name
                %p.buy-item-price.bold
                  = number_to_currency(@product.price,format: "%u%n",unit:"¥",precision: 0)
                  %span.item-shipping-fee.f14.bold
                    (税込)送料込み
      %section.buy-content.buy-user-info
        .buy-content-inner
          %ul.buy-price-table
            %li.buy-price-row.buy-you-pay.bold
            %li.buy-price-cell 支払い金額
            %br
            %li.buy-price-cell
              = number_to_currency(@product.price,format: "%u%n",unit:"¥",precision: 0)
          %section.buy-content.buy-user-info
        .buy-content-inner
          %h3 支払方法
        .buy-content-inner
          %h3 配送先
          %address.buy-user-info-text
            =@address.postal_code
            %br
            =@product.prefecture.name
            %br
            =@address.city
            =@address.block_number
            =@address.apartment_name	
            %br
            =current_user.last_name
            =current_user.first_name
          %section.buy-content.buy-user-info
          =link_to purchased_product_path, class:"purchase" do
            購入する

app/views/products/index.html.haml
.wrapper
  = render "number1"
  = render "number2"
  = render "number3"

app/views/products/purchased.html.haml
.mypage 
  %main.mypage-contents.clearfix
    .main-content
      .payment
        .payment-content
          .payment-content__title
            %h1.payment-header 購入が完了しました
          .logout-content
          =link_to root_path, class:"btn-default btn-red" do
            トップページへ戻る

app/views/products/show.html.haml
.show__all
  - if user_signed_in?
    - if @product.status == "display"
      = render 'show-sign_in'
    - else
      = render 'show-sold_out'
  - else
    - if @product.status == "display"
      = render 'show-sign_out'
    - else
      = render 'show-sign_out_sold_out'