config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  resources :products, except: [:index]
    resources :mid_category, only: :new
    resources :small_category, only: :new


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      "users/sessions"
  }
  devise_scope :user do
    get '/users', to: redirect("/users/sign_up")
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]do
    member do   
      get 'logout'
    end
  end  

  
 


  post '/products/:id/purchase',to: 'products#purchase'
  get 'products/new/mid_category', to: 'products#mid_category'
  get 'products/new/small_category', to: 'products#small_category'
 

  resources :products do
    member do
      post 'purchase'
      get 'buy'
      get 'purchased'
    end  
    get 'products/new/mid_category', to: 'products#mid_category'
    get 'products/new/small_category', to: 'products#small_category'
  end  
  
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample78D
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    %header.boss
      .header-inner 
        .header-inner__main
          %h1.header-inner__main--icon
            %a.header-inner__main--icon__img
              = link_to root_path, class: "exhibit__footer__logo" do
                =image_tag("material/logo/logo.png", width:"160",height:"50" )
          .header-inner__main--search-box
            %form.header-inner__main--search-box__form{"accept-charset" => "UTF-8", action: "#", method: "get"}
              %input.header-inner__main--search-box__form__input{name: "utf8", type: "hidden", value: "✓"}
              %input#searchInput.header-inner__main--search-box__form__input{name: "key", placeholder: "キーワードから探す"}
              %button.header-inner__main--search-box__form__button{type: "submit"}
                .header-inner__main--search-box__form__button__icon
                  = image_tag 'material/icon/icon-search1.png', alt: 'search', class: 'header-inner__main--search-box__form__button__icon__img'
              %input{name: "authenticity_token", type: "hidden"}
          %ul.header-inner__main--resultlist
          -# ここからナビバー
        .header-inner__nav
          %ul.header-inner__nav--lists-left
            %li.header-inner__nav--lists-left__item.header-inner__nav--lists-left__item__first
              =link_to "カテゴリー","#",class: "header-inner__nav--lists-left__item"
            %li.header-inner__nav--lists-left__item
              =link_to "ブランド","#",class: "header-inner__nav--lists-left__item"
          %ul.header-inner__nav--lists-right    
            - if user_signed_in?
              %li.header-inner__nav--lists-right__login
                = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-inner__nav--lists-right__logout"
              %li.header-inner__nav--lists-right__new
                =link_to "マイページ", user_path(current_user.id),class: "header-inner__nav--lists-right__mypage", local: true 
            - else  
              %li.header-inner__nav--lists-right__login
                =link_to "ログイン",new_user_session_path,class: "header-inner__nav--lists-right__login"
              %li.header-inner__nav--lists-right__new
                =link_to "新規会員登録", new_user_registration_path,class: "header-inner__nav--lists-right__new"
    = yield
    -# フッター
    %footer
      %aside.appBanner
        .appBanner__inner
          %h2.appBanner__inner--title
            だれでもかんたん、人生を変えるフリマアプリ
          %p.appBanner__inner--text
            今すぐ無料ダウンロード
          .appBanner__inner--icon
            = link_to (image_tag "app-store.svg"), "#" ,class: "appBanner__inner--icon"
            = link_to (image_tag "gougleplay.svg"),"#",class: "appBanner__inner--icon"
      .bottm-footer
        %ul.bottm-footer__contents
          %li.bottm-footer__contents--content
            %h2.bottm-footer__contents--content__head
              FURIMAについて
            %ul
              %li
                = link_to "会社概要（運営会社）","#",style: "color: white"
              %li
                = link_to "プライパシーポリシー","#",style: "color: white"
              %li
                = link_to "FURIMA利用規約","#",style: "color: white"
              %li
                = link_to "ポイントに関する規約","#",style: "color: white"
          %li.bottm-footer__contents--content
            %h2.bottm-footer__contents--content__head
              FURIMAを見る
            %ul
              %li
                = link_to "カテゴリ一覧","#",style: "color: white"
              %li
                = link_to "ブランド一覧","#",style: "color: white"
          %li.bottm-footer__contents--content
            %h2.bottm-footer__contents--content__head
              ヘルプ＆ガイド
            %ul
              %li
                = link_to "FURIMAガイド","#",style: "color: white"
              %li
                = link_to "FURIMA利用ガイドライン","#",style: "color: white"
              %li
                = link_to "お知らせ","#",style: "color: white"
        .bottm-footer__logo
          = link_to (image_tag "material/logo/logo-white.png",class: "bottm-footer__logo--icon"), "#" 
        %p
          © FURIMA
      =link_to new_product_path do
        .purchaseBtn
          %span.purchaseBtn__text
            出品する
          = image_tag "material/icon/icon_camera.png",class: "purchaseBtn__img"
        